[package]
name = "testaustime-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version = "1.4", features = ["mysql", "chrono"]}
rocket = "0.5.0-rc.1"
chrono = "0.4"
