[package]
name = "testaustime-rs"
version = "0.1.0"
edition = "2021"
authors = ["Ville Järvinen <jarvinenville606@gmail.com>", "Luukas Pörtfors <lajp@iki.fi>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.1", features = ["macros","openssl"] }
actix = "0.13"
awc = "3.0.0-beta.21"
dashmap = "5.1"
log = "0.4"
env_logger = "0.9"
diesel = { version = "1.4.8", features = ["mysql", "chrono", "r2d2"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
url = "2.2"
rand = "0.8"
futures-util = "0.3"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
anyhow = "1.0"
argon2 = "0.3.4"
testausratelimiter = { path = "testausratelimiter" }
